In [2]:
import numpy as np 
from copy import deepcopy

In [3]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
odd_arr = arr[arr % 2 == 1]
odd_arr

array([1, 3, 5, 7, 9])

In [5]:
minus_arr = deepcopy(arr)
minus_arr[minus_arr % 2 == 1] = -1
print(minus_arr)
print(arr)

# OR
minus_arr2 = np.where(arr % 2 == 1, -1, arr)
print(minus_arr2)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [6]:
# Reshaping array
arr = np.arange(10)
arr_res = arr.reshape(2, -1)
print(arr_res)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
# stacking arrays vertically
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

c = np.concatenate([a, b], axis=0)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [8]:
# stacking arrays horizontally
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

c = np.concatenate([a, b], axis=1)
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [9]:
# generating custom sequences
a = np.array([1, 2, 3])
np.r_[np.repeat(a, 3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [12]:
# common part of adrrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a, b)
print(c)

[2 4]


In [18]:
# delete elements of array that exists in the other array
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

c = np.setdiff1d(a, b)
print(c)

[1 2 3 4]
